name: Telegram Hello Bot

on:
  schedule:
    - cron: '30 1 * * *'  # Runs every day at 1:30 AM UTC (which is 7:00 AM IST)
    - cron: '30 11 * * *' # Runs every day at 11:30 AM UTC (which is 5:00 PM IST)
  workflow_dispatch:  # Allows manual triggering

jobs:
  send-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the script
        run: |
          python send_hello.py
